### PR TITLE
Moved coding competition to past events, added google talk event

### PR DESCRIPTION
**Pull request by katdrobnjakovic**

### CODE REVIEW

**Comment by CraigBryan** [comment]
Hey Kat, just saw this now.

I remember that you added the stuff to the schema because your local master seemed to say that those things already existed (and so you added them as to not change the schema on master). But apparently master actually doesn't have those (if you look at the commits for this PR, you'll see what I mean). We should probably remove those to avoid doing crazy things to the live version.

**Comment by katdrobnjakovic** [comment]
This is what I added to schema, from what I can tell it does exist on master. Could you clarify? Thanks 

create_table "blog_posts", force: :cascade do |t|
    t.datetime "created_at",                   null: false
    t.datetime "updated_at",                   null: false
    t.string   "title",                        null: false
    t.boolean  "is_published", default: false
    t.date     "published_on"
    t.integer  "user_id"
    t.text     "body_field"
  end

  add_index "blog_posts", ["user_id"], name: "index_blog_posts_on_user_id", using: :btree

  create_table "users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet     "current_sign_in_ip"
    t.inet     "last_sign_in_ip"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "username",                            null: false
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree

**Comment by CraigBryan** [comment]
Yarrr. You be right.

My brain is not working particularly well today. Sorry!

**Comment by katdrobnjakovic** [comment]
No worries! Thanks :)

**Comment by CraigBryan** [comment]
But also, this is out of date now (due to my lack of speed merging it), and the code competition is a "Past Event" now.

**Comment by katdrobnjakovic** [comment]
Yup, I am currently fixing that and adding the new Google talk event! There will be an updated PR in a minute! :)

**Comment by katdrobnjakovic** [comment]
Okay, updated this PR to have the new Google Maps Talk event and moved the Coding Competition event to past events.

**Comment by CraigBryan** [comment]
Looks good. I'll check it real quick locally soon.

**Comment by CraigBryan** [comment]
I think master is in a bad state (it has the not so pretty headshots layout at the moment). So I don't know if I can update heroku easily (I'll have to do some git magic)

**Comment by katdrobnjakovic** [comment]
I must have messed that up on mine, sorry! Let's not rush it.

**Comment by CraigBryan** [comment]
No, not your fault. Because Alex's last PR was on master, and I was in a hurry, I quickly merged the PR before looking at it locally. So the new layout of profiles is there and not everyone agrees on the way it makes things look. My solution at the time was to leave master the way it was and avoid pushing to Heroku until I (or someone else) could fix it.

**Comment by katdrobnjakovic** [comment]
Ah okay! I can come up with an option now and post some screen shots so we can get master up and running. The google talk event is an important one to the Faculty.

**Comment by CraigBryan** [comment]
That would be immensely helpful. I feel like garbage today, so it's hard to focus.

**Comment by katdrobnjakovic** [comment]
Hope you feel better :)

**Pull request merged**
