### PR TITLE
Fixed awk spacing of Past Events

### PR DESCRIPTION
**Pull request by nelmarianna**
Deleted the div and got rid of positioning, now it looks okay. Or so I hope!

### CODE REVIEW

**Comment by charle692** [comment]
Awesome you did it! I'll check it and merge it once I know it's good to go.

**Comment by CraigBryan** [comment]
@nelmarianna The only thing I'd change about your PR is to make the changes in some branch other than master. To do this, make sure you do `git checkout -b whatever_thing_you_want_to_name_your_super_descriptive_branch` and make the changes there, commit, push that branch to your remote (github) repo. Then make this PR. Hope that makes sense!

**Comment by CraigBryan** [comment]
I've tested this change anyway, so I'll merge. Good work @nelmarianna

**Comment by CraigBryan** [comment]
Closes #49

**Pull request merged**
