### PR TITLE
Began working on events page - banners

### PR DESCRIPTION
**Pull request by getaclue00**
# do not merge

Testings things out - decoupling some code, trying base64
- [x] base64 images - restrict image size in future, under 10 mb
- [x] remove code duplication
- [x] upload
- [x] fetch
- [x] remove code from controller in future
- [ ] remove images from assets

### CODE REVIEW

**Comment by getaclue00** [comment]
Think I am gonna do a different direction than what I thought of, so:
- create Events Model
- Events(name, facebook_url, image_url, image_url_base64, description, date, time) 
- name required, date required, time required
- debate between clientside and serverside encoding

http://www.postgresql.org/docs/9.1/static/datatype-datetime.html

**Comment by charle692** [comment]
hey @getaclue I was reading up on base64 encoding. And I'm not sure it's the right thing to use. bas64 encoding images gets rid of any caching advantages.

**Comment by getaclue00** [comment]
@charle692 yup, aware of that (: but, at this point, I am not too concerned about caching. 

I guess on the whole, I just wanted to experiment with firebase. Encode images, have an uploader to firebase, and fetch from firebase on each request. That works fine...

I think I'll experiment with base64 for smaller images... I'm guessing 100px*100px range... maybe smaller.

I was actually thinking of just leaving it as is... I do want to add a banner model and store it... hence adding an upload capability. I was thinking of playing with https://www.cloudflare.com/plans/ but that involves playing with CNAMES... and I'm not sure how all of that is configured on heroku/ whether or not that is worth the hassle... Which brings me to the following:
- (1) leave it as is? Just move it to database and store the relative assets location. 
  Or... 
- (2) one more thing I wanted to play with... have an uploader to static firebase directory... but haven't figured out how to sync asset copies. So, what I am thinking is precompiling assets --> uploading with the correct digest to firebase --> saving the link to image to database --> when we build the images page... simply iterate through images and grab the relative firebase url.

**Comment by charle692** [comment]
@getaclue we could also just use the free AWS tier which would give us 5GB of storage. And then use Paperclip to do the image processing on upload. Paperclip also has a AWS plugin. So adding this in would take little to no time. We can create one model called image.

Event has_many images
TeamMember has_one image

That way we could use the one model for multiple things.

**Comment by charle692** [comment]
I was planning on working on the team member backend during the break so that we don't have to push code all the time. We should actually talk with the rest of the team on this and see what they think.

**Comment by getaclue00** [comment]
@charle692 ya we could use the tier, but we'll run into the trouble where we have to pay after the 1st year? so we'll have to redo it again in a year? I mean its not a big deal - but why not just do it correct from start? . Personally, I dont think we should go the AWS route. Don't take me wrong, I love using S3. It's stupid easy, you can have a lot of control over files... but it does come with a price and it's for 12 months.

I was thinking of it a bit differently.

just store the relative url for the image object in the database as a string, and fetch the link when needed.
when we upload a new image --> just upload the image into that location (or to two locations to ensure redundancy) --> save the image with the url.

Yeah it's a good idea to get feedback. Or you could just do it and we have to live with it =P

**Comment by getaclue00** [comment]
So, to update.

I looked into different variations... and just storing it in our database as a binary seems the cheapest/easiest at the moment. Moved everything regarding the events into the database.

Can create a new event using simple events/new link.

I'll post the link to a test in our chat.

Just need to add auth to our app... and verify permission in this section.

I kind of don't want to use the idea of login/logout and, instead, we could just give out tokens as we need to... but my feeling towards this can definitely change.

**Pull request closed without merging**
