### PR TITLE
Updated Arash's photo / Added Team Members personal websites

### PR DESCRIPTION
**Pull request by katdrobnjakovic**

### CODE REVIEW

**Comment by CraigBryan** [comment]
I just tested this out.

Because the effect is sublet, its probably ok to merge this and see what we can do that we like better later. That way we get the changes for Arash done with now.

Thoughts?

**Comment by mtuck063** [comment]
There is a glare coming from Arash's glasses in this new photo. We should probably keep the older one. Did he ask for the change?

**Comment by mtuck063** [comment]
I accidentally merged Kats request to the master repo.

**Comment by charle692** [comment]
We could ask Phillipe to remove the glare or at least minimize it.

**Comment by katdrobnjakovic** [comment]
He had requested the photo. We can ask him to choose another one (if there is one available) or see if we can edit it.

**Comment by CraigBryan** [comment]
I say we leave him to choose it. We can tell him the photo has glare, and if he doesn't care, then I don't really either. If he does care, we'll ask Alex or Philippe to take a look at it.

**Comment by katdrobnjakovic** [comment]
Yes, I agree.

**Pull request merged**
