### PR TITLE
install instructions for mac using homebrew

### PR DESCRIPTION
**Pull request by oluwatimio**

### CODE REVIEW

**Comment by nelmarianna** [comment]
From a UI/UX pov it's weird to have step 1 and step 1... maybe we can think of a better way to display this?

**Comment by oluwatimio** [comment]
I could indicate the first one is for ubuntu/linux. 

Currently it's just install rbenv (ruby version manager) which I agree can be confusing especially with the mac steps being below that.

Step 1a

install rbenv (ruby version manager) for linux/ubuntu

Below that, we would have 

Step 1b
install rbenv (ruby version manager) for mac

How does that sound?

**Comment by nelmarianna** [comment]
Hmmm what about something like
###  step 1: install rbenv
#### for windows or whatever platform
details

#### for mac
details

**Comment by oluwatimio** [comment]
Alright. Sounds good! I just made the changes.

**Comment by nelmarianna** [comment]
Use three #'s for the subtitles for windows, for linux, and for mac. Ian will need to look over the commands, I'm just doing UI checking :)

**Comment by ianDesson** [comment]
Change it from "To run application" to "Install Gems" as bundler install doesn't run the application; "rails s" does. Also, since we added 2 new sections, In the Windows section we say "From this tutorial" which is now ambiguous, please change it to "From the Linux tutorial". Other than that, the commands seem fine, I can't test on a mac machine right now but, most tutorials say to use the same commands so, if it worked for you and everybody else is saying to use that, it's fine with me. Good work!

**Comment by oluwatimio** [comment]
Just made the changes

**Pull request merged**
